include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - annotate_overrides
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - await_only_futures
    - comment_references
    - hash_and_equals
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_final_locals
    - prefer_void_to_null
    - unnecessary_overrides
