name: armv4t

description: >
  An emulator for the ARMv4T instruction set, written in Dart.
version: 0.1.0

homepage: https://github.com/matanlurey/armv4t.dart

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  binary: ^1.7.0
  collection: ^1.14.12
  meta: ^1.1.8

dev_dependencies:
  goldenrod: ^0.1.0
  pedantic: ^1.9.0
  path: ^1.7.0
  test: ^1.15.0
  test_coverage: ^0.4.1

dependency_overrides:
  binary:
    git:
      url: https://github.com/matanlurey/binary.dart
      ref: dd6a27811e24260215a56bb3b9a9119a88bc8b51
