name: armv4t

description: >
  An emulator for the ARMv4T instruction set, written in Dart.
version: 0.1.0

homepage: https://github.com/matanlurey/armv4t.dart

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  args: ^1.6.0
  binary: ^2.0.0
  collection: ^1.14.12
  meta: ^1.1.8

dev_dependencies:
  glob: ^1.2.0
  goldenrod: ^0.1.0
  pedantic: ^1.9.0
  path: ^1.7.0
  test: ^1.15.0
  test_coverage: ^0.4.1

executables:
  debug:
  disassemble:
