name: Dart

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dart
        uses: cedx/setup-dart@v2

      - name: Fetch Dependencies
        run: pub get

      - name: Dart Format
        run: dartfmt . --set-exit-if-changed

      - name: Dart Analyzer
        run: dartanalyzer . --fatal-warnings

      - name: Test
        run: pub run test --reporter expanded

      - name: Generate Coverage
        run: pub run test_coverage --no-badge

      - name: Upload Coverage
        uses: codecov/codecov-action@v1.0.7
